source "http://rubygems.org"
gem "rake"

require 'rubygems'
current = Gem::Version.create(RUBY_VERSION * 1)

if (current >= Gem::Version.create('1.9')) then
  p "Founded #{current} ruby, requiring 'test-unit' gem"
  gem "test-unit"
end

gem "test-spec"
