source "http://rubygems.org"

require 'rubygems'
current = Gem::Version.create(RUBY_VERSION * 1)

gem "rake"

gem "test-unit"

if (current < Gem::Version.create('2.2')) then
  gem 'activesupport', '<5.1'
end

gem "shoulda"
