source "http://rubygems.org"
require 'rubygems'
current = Gem::Version.create(RUBY_VERSION * 1)

gem "rake"

gem "rspec"
gem "json"

gem "gherkin"

if (current < Gem::Version.create('2.2')) then
  gem "cucumber", '<3'
else
  gem "cucumber", '<4'
end
