# Created by IntelliJ IDEA.
# User: Roman.Chernyatchik
# Date: 27.12.2007
# Time: 21:52:23
# To change this template use File | Settings | File Templates.

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

#############################################
Dir["tasks/**/*.rake"].sort.each {|ext| load ext}