source "http://rubygems.org"

require 'rubygems'
current = Gem::Version.create(RUBY_VERSION * 1)

# rake 10.2.0 does not supports less than ruby-1.9
if (current < Gem::Version.create('1.9')) then
  gem "rake", '<2.10.1'
else
  # Rake 11.0.1 removes the last_comment method which Rails 2.3 rspec-core (< 3.4.4) uses
  # From http://stackoverflow.com/a/35893625/1039742
  gem 'rake', '< 11.0'
end

gem "rspec", "~> 2.0", '< 2.99'
