source "http://rubygems.org"
require 'rubygems'
current = Gem::Version.create(RUBY_VERSION * 1)

# rake 10.2.0 does not supports less than ruby-1.9
if (current < Gem::Version.create('1.9')) then
  gem "rake", '<2.10.1'
else
  gem "rake"
end

gem "rspec"
gem "json"

# gherkin 2.12.1 does not supports ruby-1.8.7
if (current < Gem::Version.create('1.9')) then
  gem "gherkin", '<2.11.1'
elsif (current > Gem::Version.create('1.9')) then
  gem "gherkin", '>2.11.0'
end

gem "cucumber", "~>1.3"
